### ISSUE TITLE
This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery

### ISSUE THREAD

**Issue by sbc640964** [hammerstonedev/fast-paginate#13]
I did not install the package
But I'm manually trying to create such a query and that's the error
**This version of MySQL does not yet support 'LIMIT & IN / ALL / ANY / SOME subquery**
My version is mysql  Ver 8.0.29 for Win64 on x86_64 (MySQL Community Server - GPL)

**Comment by aarondfrancis** [comment]
In the Laravel code we actually execute the queries separately to get around that issue! We bind the raw values into the query instead of using a subquery.

https://github.com/hammerstonedev/fast-paginate/blob/main/src/BuilderMixin.php#L40
