### ISSUE TITLE
Error with UUID Column in Notifications Column

### ISSUE THREAD

**Issue by seanfoushee** [hammerstonedev/fast-paginate#17]
I have a new issue now that #16 solved the orderBy error. When utilizing fastPaginate with a table using a UUID column the sub query fails:

`production.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column '53b79b97' in 'where clause' (SQL: select * from notifications where notifications.notifiable_type = App\Models\User and notifications.notifiable_id = 3 and notifications.notifiable_id is not null and notifications.id in (53b79b97-d794-4260-9b74-c4e78d01d870) order by created_at desc limit 11 offset 0)`

Note the column the query is attempting to read is the first part of the UUID in the notifications table. I assume escaping the ids in the case they're not integers would be the solution.

**Comment by aarondfrancis** [comment]
@seanfoushee ah, good call. Can you check #18 and see if that works for you?

**Comment by seanfoushee** [comment]
@aarondfrancis that fixed it! Thanks.

**Comment by aarondfrancis** [comment]
Great! Published `v0.1.5`
