### ISSUE TITLE
Count on pages is off by one from provided per_page

### ISSUE THREAD

**Issue by joecampo** [hammerstonedev/fast-paginate#2]
Hey, sorry to ping you on this.

One thing I've run into is [this line](https://github.com/hammerstonedev/deferred-pagination-macro/blob/801a8c4d912a75090c782d5a520915b09c2dfa64/macro.php#L31) seems to cause the count on a page to be off-by-one.

So for instance, if there are 5 `Post` records, and I set `per_page=5` I would expect that we'd get back all 5 on the same page, but what I'm actually seeing (below) is 4.

Removing the decrement on line 31 seems to resolve the issue, but I couldn't grok why it is necessary to do so before passing it to `simplePaginate`.

Apologies if I'm missing something obvious here.

![image](https://user-images.githubusercontent.com/3619398/151050839-3288df24-4e3b-40b2-b036-6ba160845da0.png)

**Comment by aarondfrancis** [comment]
Doh, you're absolutely right. I was watching the SQL not the output. Let me updated. Turns out *I'm* the one missing something obvious!

**Comment by aarondfrancis** [comment]
Making this a package, I think I fixed this!
