### ISSUE TITLE
[Question] Sort order is changed when using `fastPaginate` compared to `paginate`

### ISSUE THREAD

**Issue by Naoray** [hammerstonedev/fast-paginate#32]
I wasn't able to pinpoint where it happens and why, but using `paginate()` I get the results ordered by `created_at desc`, while using `fastPaginate()` does return the results as if ordered by `created_at asc`.

In my example the primary keys are `uuids` -> could this be the issue?

**Comment by aarondfrancis** [comment]
@Naoray can you give me a little more info? I have [a test](https://github.com/hammerstonedev/fast-paginate/blob/ea5bae048e3b838801713baf016bdd2b547103c4/tests/Integration/BuilderTest.php#L132) that ensures the order is propagated from the outer query to the inner query, but there might be a case that I missed.

Can you boil it down to a reproducible case? Thanks!

**Comment by Naoray** [comment]
@aarondfrancis s. test I added in #34.

**Comment by aarondfrancis** [comment]
To anyone reading this in the future: see #34 for explanations. Closing.
