### ISSUE TITLE
Can't using pros of Eager Loading

### ISSUE THREAD

**Issue by yavgel85** [hammerstonedev/fast-paginate#4]
When using paginate() -> all fine:
 
 $timelines  = Timeline::select('id', 'user_id', 'description', 'created_at')->with('user:id,username')->where('client_id', $client->id)->latest('id')->paginate(10, ['*'], 'timeline');
 
![with() with paginate](https://user-images.githubusercontent.com/18446527/151403384-9445c166-64c0-4155-9c1f-2e2d5da9e348.png)

But when using deferredPaginate  -> it not exclude duplicate queries and models:

$timelines         = Timeline::select('id', 'user_id', 'description', 'created_at')->with('user:id,username')->where('client_id', $client->id)->latest('id')->deferredPaginate(10, ['*'], 'timeline');

![with() with deferredPaginate](https://user-images.githubusercontent.com/18446527/151403454-edb669c6-e432-4e9a-af1d-ab6b90e054a7.png)

**Comment by aarondfrancis** [comment]
Making this a package. If you are still running into this, please let me know and we can add a test for it!
