### ISSUE TITLE
Use with QueryBuilder/DB

### ISSUE THREAD

**Issue by kieran-s** [hammerstonedev/fast-paginate#45]
Is there any way to use this with the DB query builder (i.e. DB::select() ) ? Or can it only be used with eloquent?

If not, could it possibly be implemented?

**Comment by aarondfrancis** [comment]
Unfortunately not, as this package relies on the getting the primary key from the model, which is not possible with the base builder.

**Comment by imsorx** [comment]
Maybe accept a optional parameter for primary key when using caller with DB facade?
PHP 8's named parameters will also make it easy.
