### ISSUE TITLE
Ide highlighting 

### ISSUE THREAD

**Issue by hamzaelmaghari** [hammerstonedev/fast-paginate#46]
Hello,
It is not an issue, in fact, just a quality improvement. when I started using `Laravel fastPaginate` the idle `(Phpstorm)` in my case highlights my code when I use `$uqery->fastPaginate()` although using idle helper which is [Laravel Idea](https://github.com/laravel-idea/plugin/).

<img width="806" alt="screenshot 5" src="https://user-images.githubusercontent.com/84163115/211636124-49d5d433-211b-44d6-a20c-ff8e5564dce1.png">

**Comment by ankurk91** [comment]
You can use IDE-Helper package which can help.

**Comment by hamzaelmaghari** [comment]
I already using Laravel Idea which is for that.

**Comment by aarondfrancis** [comment]
I'm not sure how to fix this! Happy to change anything here if I need to, feel free to reopen.
