### ISSUE TITLE
Integrity constraint violation: 1052 Column 'created_at' in order clause is ambiguous

### ISSUE THREAD

**Issue by fviip** [hammerstonedev/fast-paginate#47]
'php
$tags = $post->tags()->orderBy('created_at', 'desc')->fastPaginate(20);
'

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in order clause is ambiguous

**Comment by parallels999** [comment]
Show the SQL

**Comment by aarondfrancis** [comment]
I'm not sure this is a fastPaginate problem. Can you show the SQL or schema? Does it work with the traditional `paginate` method?
