### ISSUE TITLE
Does not respect the model's collection class

### ISSUE THREAD

**Issue by andrewtweber** [hammerstonedev/fast-paginate#50]
First of all, a little strange that it returns an `Illuminate\Support\Collection` instead of `Illuminate\Database\Eloquent\Collection`. Is there a reason for that?

But also, if you [set a custom collection](https://laravel.com/docs/10.x/eloquent-collections#custom-collections) by overriding a model's `newCollection` method, it should use that collection class instead.

I'll work on a fork if I have time, thanks for the package

**Comment by aarondfrancis** [comment]
Fixed in https://github.com/hammerstonedev/fast-paginate/pull/38.
