### ISSUE TITLE
FastPaginate on collection aggregation

### ISSUE THREAD

**Issue by MagnusDot** [hammerstonedev/fast-paginate#53]
on our project, we would like to use this library completely but we are doing collection aggregation and currently you don't support this, is it possible to do this? or should we continue using paginate() for collections?

**Comment by MagnusDot** [comment]
![image](https://github.com/hammerstonedev/fast-paginate/assets/39904918/ce07d95e-873e-4ffd-92b8-d2941c52dcfa)
i've got this type of errors

**Comment by aarondfrancis** [comment]
It doesn't make sense to `fastPaginate` a collection, since you've already got all the records. There isn't even a `paginate` method on a collection, so I don't think there should be a `fastPaginate`.

**Comment by aarondfrancis** [comment]
See also https://github.com/hammerstonedev/fast-paginate/issues/23

**Comment by MagnusDot** [comment]
Hello @aarondfrancis  , thank you for your quick answer, but there is indeed a paginate method on the collections currently

![image](https://github.com/hammerstonedev/fast-paginate/assets/39904918/5ae22b99-57ab-4bdd-bf7f-429aacdefd4e)
![image](https://github.com/hammerstonedev/fast-paginate/assets/39904918/57ca450f-8a5d-4ce4-95e4-089308784844)

**Comment by MagnusDot** [comment]
but you are right that there is no need for fastpaginate as the requests have already been made, thank you for your time and sorry for the stupid question

**Comment by aarondfrancis** [comment]
Hmm that's weird. I'm looking in the source code and I'm not seeing a `paginate` method. Maybe a package is adding it?

<img width="448" alt="image" src="https://github.com/hammerstonedev/fast-paginate/assets/881931/5685161a-5359-4896-ad97-bd8fddd2b7b6">

<img width="920" alt="image" src="https://github.com/hammerstonedev/fast-paginate/assets/881931/97175505-506a-4ed9-8878-1f2639c9a461">

Is there any way you could point me to the collection `paginate` method?

> sorry for the stupid question

Not a stupid question!

**Comment by MagnusDot** [comment]
after some research, i found that it was a macro created by spatie lavavel livewire wizard that added the pagination on the collections like this

**Comment by aarondfrancis** [comment]
Ah ha! I wondered where that was coming from. Thank you for reporting back!
