### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by marlonbasten** [hammerstonedev/fast-paginate#60]
This package is really useful, but Laravel 11 isn't supported yet. As there are no obvious breaking changes in Laravel 11, could you update the composer.json? Thanks!

**Comment by sidis405** [comment]
For the time being you can use #58 and specifically have a look at https://github.com/hammerstonedev/fast-paginate/pull/58#issuecomment-1973491067 on how to use

**Comment by binaryfire** [comment]
I don't think this should have been closed? The package still doesn't support Laravel 11 and this was the only open issue re: that point.

**Comment by marlonbasten** [comment]
> I don't think this should have been closed? The package still doesn't support Laravel 11 and this was the only open issue re: that point.

@binaryfire You're right! I reopened it. I thought it would be pointless as it is abandoned, but it's worth a try!

**Comment by crazynds** [comment]
Unfortunately I will stop using the package due to the lack of support from the maintainer. I'm updating my laravel project and will no longer use fast paginate.

**Comment by aarondfrancis** [comment]
Merged! Thanks for your patience.
